version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/P@ssw0rd"
    volumes:
      - neo4j_data:/var/lib/neo4j

  web:
    image: sasansharifipour/research_assistant:latest 
    container_name: web_app
    ports:
      - "8080:8080"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
